name: Twitter Notifications

on:
  schedule:
    # every 15 minutes the job will run
    - cron: "*/15 * * * *"
  push:
    branches:
      - master

jobs:
  update-json-data:
    runs-on: ubuntu-latest
    timeout-minutes: 14

    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Cache pip
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install Python dependencies
      run: pip3 install -r requirements.txt
    - name: Run scanning script
      run: |
        python3 twitter_notifications.py
      env:
          MONITOR_BOT_TOKEN: ${{ secrets.MONITOR_BOT_TOKEN }}
          DATA_OPS_CHAT_ID: ${{ secrets.DATA_OPS_CHAT_ID }}
          TWITTER_CREDENTIALS: ${{secrets.TWITTER_CREDENTIALS}}
        env:
          status: ${{job.status}}